service: sls-wsgi-rqs-test

custom:
  wsgi:
    app: project.wsgi.application
  pythonRequirements:
    fileName: requirements_serverless.txt
    useDownloadCache: false
    useStaticCache: false
    dockerizePip: true
    dockerFile: Dockerfile
    dockerExtraFiles:
      - /usr/lib64/mysql/libmysqlclient.so.18
plugins:
  - serverless-wsgi
  - serverless-python-requirements
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  environment:
    DB_NAME: ${opt:db_name}
    DB_USER: ${opt:db_user}
    DB_PASSWORD: ${opt:db_password}
    DB_HOST: ${opt:db_host}